import type { Metadata } from "next";
import { Outfit, Unbounded } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const unbounded = Unbounded({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-unbounded",
});

export const metadata: Metadata = {
  title: "Join Waitlist - SalesRocket360",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(outfit.variable, unbounded.variable)}>
        {children}
      </body>
    </html>
  );
}
